"""Remove isDislik column in engagements

Revision ID: 6d2bafab7237
Revises: 872ad5d4b420
Create Date: 2021-06-30 19:31:48.854913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2bafab7237'
down_revision = '872ad5d4b420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagements', 'isDisLiked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagements', sa.Column('isDisLiked', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
